apiVersion: v1
kind: Service
metadata:
  name: nextjs-math-api
  namespace: default
spec:
  selector:
    app: nextjs-math-api
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP